from __future__ import annotations

from datetime import date
from pathlib import Path

from briarwood.reports.renderer import render_tear_sheet_html
from briarwood.reports.schemas import TearSheet
from briarwood.reports.tear_sheet import build_tear_sheet
from briarwood.schemas import AnalysisReport


_PRINT_CSS = """
@page {
    size: Letter portrait;
    margin: 0.75in 0.75in 1in 0.75in;

    @bottom-center {
        content: "Generated by Briarwood \00b7 """ + "{gen_date}" + """ \00b7 Confidential";
        font-family: Georgia, "Times New Roman", serif;
        font-size: 9px;
        color: #8b7c67;
        letter-spacing: 0.04em;
    }

    @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
        font-family: Georgia, "Times New Roman", serif;
        font-size: 9px;
        color: #8b7c67;
    }
}

/* Force light background for print */
body {
    background: #f5f1e8 !important;
    color: #17212b !important;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
}

/* Page width — remove max-width so content fills the page */
.page {
    max-width: none;
    padding: 0;
}

/* Page breaks before major sections */
.verdict-card {
    page-break-inside: avoid;
}

.signal-metrics-section {
    page-break-before: always;
    page-break-inside: avoid;
}

.chart-card {
    page-break-before: always;
    page-break-inside: avoid;
}

.durability-card {
    page-break-before: always;
    page-break-inside: avoid;
}

.carry-card {
    page-break-before: always;
    page-break-inside: avoid;
}

.comp-card-section {
    page-break-before: always;
}

.scenario-cases {
    page-break-before: always;
}

.evidence-card {
    page-break-before: always;
    page-break-inside: avoid;
}

/* Prevent orphaned cards */
.card {
    page-break-inside: avoid;
}

.case-card {
    page-break-inside: avoid;
}

.comp-card {
    page-break-inside: avoid;
}

.carry-subcard {
    page-break-inside: avoid;
}

/* Ensure grids wrap properly on narrower print width */
.comp-grid {
    grid-template-columns: repeat(2, 1fr);
}

.case-grid {
    grid-template-columns: repeat(2, 1fr);
}

/* Charts: ensure SVGs render within page bounds */
.scenario-chart-wrap {
    overflow: visible;
}

.scenario-chart {
    min-width: 0;
    width: 100%;
}

.chart-panel .chart {
    min-height: 0;
}

/* Hide interactive elements */
button, input, select, textarea, .slider, .toggle {
    display: none !important;
}
"""


def render_tear_sheet_pdf(
    report: AnalysisReport,
    output_path: str | Path,
) -> Path:
    """Generate a PDF tear sheet from an AnalysisReport.

    Renders the HTML tear sheet, injects print-specific CSS overrides
    (light background, page margins, section breaks, footer), and
    converts to PDF via weasyprint.
    """
    import weasyprint

    tear_sheet = build_tear_sheet(report)
    return render_pdf_from_tear_sheet(tear_sheet, output_path)


def _build_cover_page(tear_sheet: TearSheet, gen_date: str) -> str:
    """Build an HTML cover page block to inject before the main content."""
    from html import escape
    h = tear_sheet.header
    c = tear_sheet.conclusion
    property_name = escape(h.property_name)
    subtitle = escape(h.subtitle)
    stance = escape(h.investment_stance)
    verdict = escape(c.verdict)
    ask = f"${c.ask_price:,.0f}" if c.ask_price else "—"
    bcv = f"${c.briarwood_current_value:,.0f}" if c.briarwood_current_value else "—"

    return f"""
    <div class="cover-page" style="
        display: flex; flex-direction: column; justify-content: center; align-items: center;
        min-height: 100vh; text-align: center; page-break-after: always;
        font-family: Georgia, 'Times New Roman', serif;
    ">
        <div style="margin-bottom: 48px;">
            <div style="font-size: 14px; letter-spacing: 0.2em; text-transform: uppercase; color: #8b7c67; margin-bottom: 12px;">
                Briarwood Capital
            </div>
            <div style="font-size: 11px; letter-spacing: 0.15em; text-transform: uppercase; color: #a09080;">
                Property Analysis
            </div>
        </div>
        <div style="margin-bottom: 40px;">
            <h1 style="font-size: 32px; font-weight: 700; color: #17212b; margin: 0 0 8px 0; line-height: 1.2;">
                {property_name}
            </h1>
            <div style="font-size: 15px; color: #5a5a5a; margin-bottom: 16px;">
                {subtitle}
            </div>
            <div style="font-size: 16px; font-weight: 600; color: #2c5282; letter-spacing: 0.05em;">
                {stance}
            </div>
        </div>
        <div style="
            display: flex; gap: 32px; justify-content: center; margin-bottom: 40px;
            padding: 16px 32px; border-top: 1px solid #d4c9b8; border-bottom: 1px solid #d4c9b8;
        ">
            <div>
                <div style="font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em; color: #8b7c67; margin-bottom: 4px;">Ask Price</div>
                <div style="font-size: 20px; font-weight: 700; color: #17212b;">{ask}</div>
            </div>
            <div>
                <div style="font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em; color: #8b7c67; margin-bottom: 4px;">Briarwood Value</div>
                <div style="font-size: 20px; font-weight: 700; color: #17212b;">{bcv}</div>
            </div>
        </div>
        <div style="font-size: 14px; color: #5a5a5a; font-style: italic; max-width: 480px; line-height: 1.6;">
            {verdict}
        </div>
        <div style="margin-top: 60px; font-size: 10px; color: #a09080;">
            Generated {gen_date} &middot; Confidential
        </div>
    </div>
    """


def render_pdf_from_tear_sheet(
    tear_sheet: TearSheet,
    output_path: str | Path,
) -> Path:
    """Generate a PDF from a pre-built TearSheet object."""
    import weasyprint

    html_content = render_tear_sheet_html(tear_sheet)

    # Inject print CSS before closing </style>
    gen_date = date.today().strftime("%B %d, %Y")
    print_css = _PRINT_CSS.replace("{gen_date}", gen_date)
    inject = f"\n/* PDF print overrides */\n{print_css}\n"
    html_content = html_content.replace("</style>", f"{inject}</style>", 1)

    # Inject cover page before main content
    cover_html = _build_cover_page(tear_sheet, gen_date)
    html_content = html_content.replace('<main class="page">', f'{cover_html}\n  <main class="page">', 1)

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)

    doc = weasyprint.HTML(string=html_content)
    doc.write_pdf(str(destination))
    return destination


def write_tear_sheet_pdf(report: AnalysisReport, output_path: str | Path) -> Path:
    """Convenience alias matching the HTML writer naming convention."""
    return render_tear_sheet_pdf(report, output_path)
